# Generated by Django 5.1.2 on 2024-12-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='last4',
            field=models.CharField(default='****', editable=False, max_length=4),
        ),
    ]
