# Generated by Django 5.1.3 on 2024-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_creditcard_last4"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
