# Generated by Django 5.1.2 on 2025-01-12 20:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(default=users.models.generate_tax_id, max_length=20, unique=True),
        ),
    ]
