# Generated by Django 4.1.13 on 2024-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="product",
            name="distributor_info",
            field=models.CharField(
                blank=True, default="Unknown Distributor", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(default="Unknown Model", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_in_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_status",
            field=models.CharField(default="No Warranty", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Unnamed Product", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
