# Generated by Django 5.1.2 on 2024-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="instrument",
            field=models.CharField(default="Unknown Instrument", max_length=100),
        ),
    ]
