# Generated by Django 5.1.2 on 2024-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
