# Generated by Django 5.1.2 on 2024-11-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_category_product_instrument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="instrument",
        ),
    ]
