# Generated by Django 5.1.2 on 2024-11-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
