# Generated by Django 5.1.3 on 2024-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_review_created_at_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
