# Generated by Django 5.1.2 on 2024-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_distributor_info_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
