# Generated by Django 5.1.3 on 2024-12-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
