# Generated by Django 5.1.2 on 2025-01-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
