# Generated by Django 5.1.3 on 2024-11-28 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
