# Generated by Django 5.1.2 on 2024-12-03 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('IN-TRANSIT', 'In-Transit'), ('DELIVERED', 'Delivered')], default='PROCESSING', max_length=20),
        ),
    ]
