# Generated by Django 5.1.3 on 2024-12-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_orderitem_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_return_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_return_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="requested_return_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("IN-TRANSIT", "In-Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELED", "Canceled"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
