# Generated by Django 5.1.3 on 2024-12-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="refunded_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
