# Generated by Django 5.1.3 on 2024-12-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_orderitem_refunded_quantity"),
        ("store", "0013_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="order_item_images/"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
            ),
        ),
    ]
