# Generated by Django 5.1.3 on 2025-01-12 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_delivery"),
        ("store", "0016_remove_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="address",
            new_name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="product_list",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="total_price",
        ),
        migrations.AddField(
            model_name="delivery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="products",
            field=models.ManyToManyField(related_name="deliveries", to="store.product"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="customer_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
